/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Claims = t.iface([], {
  "id": "string",
  "email": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  Claims,
};
export default exportedTypeSuite;
