/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const RegisterForm = t.iface([], {
  "userId": "string",
  "hospitalName": "string",
  "password": "string",
  "email": "string",
  "confirm_password": "string",
});

export const LoginForm = t.iface([], {
  "userId": "string",
  "password": "string",
});

const exportedTypeSuite: t.ITypeSuite = {
  RegisterForm,
  LoginForm,
};
export default exportedTypeSuite;
